export const TODO_UI_EVENT = Object.freeze({
  COMPOSER_CHANGE: 'COMPOSER_CHANGE',
  COMPOSER_COMMIT: 'COMPOSER_COMMIT',
  COMPOSER_SUBMIT: 'COMPOSER_SUBMIT',
  FLUSH: 'FLUSH',
  RETRY: 'RETRY',
  TODO_PATCH: 'TODO_PATCH',
  TODO_REMOVE: 'TODO_REMOVE',
})
