import assert from 'node:assert/strict'
import { test } from 'vitest'
import {
  createCoverageBaseline,
  evaluateCoverage,
  renderCoverageHtml,
  renderCoverageMarkdown,
} from './coverage-evidence.mjs'

const REPOSITORY_ROOT = '/repo'
const METRICS = ['statements', 'branches', 'functions', 'lines']

/** @param {number} covered @param {number} total */
const tuple = (covered, total) => ({ covered, total })

/** @param {Partial<Record<'statements' | 'branches' | 'functions' | 'lines', {covered: number, total: number}>>} [coverage] */
const fileCoverage = ({
  statements = tuple(4, 5),
  branches = tuple(2, 3),
  functions = tuple(1, 1),
  lines = tuple(4, 5),
} = {}) => ({ statements, branches, functions, lines })

/** @param {Record<string, ReturnType<typeof fileCoverage>>} files */
const summary = (files) => ({
  total: fileCoverage(),
  ...Object.fromEntries(
    Object.entries(files).map(([path, coverage]) => [
      `${REPOSITORY_ROOT}/${path}`,
      coverage,
    ])
  ),
})

/** @param {Record<string, ReturnType<typeof fileCoverage>>} files */
const baseline = (files) => ({
  schemaVersion: 1,
  notice: 'Generated by npm run coverage:ratchet. Do not edit manually.',
  files,
})

test('accepts an exact per-file baseline match', () => {
  const files = { 'shared/src/example.js': fileCoverage() }
  const evaluation = evaluateCoverage({
    summary: summary(files),
    baseline: baseline(files),
    repositoryRoot: REPOSITORY_ROOT,
  })

  assert.equal(evaluation.verdict, 'pass')
  assert.deepEqual(evaluation.changes, [])
  assert.deepEqual(evaluation.files.map(({ path, status }) => ({ path, status })), [
    { path: 'shared/src/example.js', status: 'unchanged' },
  ])
  assert.deepEqual(Object.keys(evaluation.files[0].current), METRICS)
})

test('keeps informational UI coverage outside the exact logic ratchet', () => {
  const logicPath = 'shared/src/example.js'
  const uiPath = 'frontend/src/App.jsx'
  const logicCoverage = fileCoverage()
  const evaluation = evaluateCoverage({
    summary: summary({
      [logicPath]: logicCoverage,
      [uiPath]: fileCoverage({ statements: tuple(1, 5) }),
    }),
    baseline: baseline({ [logicPath]: logicCoverage }),
    repositoryRoot: REPOSITORY_ROOT,
    gatedPaths: [logicPath],
  })

  assert.equal(evaluation.verdict, 'pass')
  assert.deepEqual(evaluation.files.map(({ path }) => path), [logicPath])
  assert.deepEqual(evaluation.global.statements, logicCoverage.statements)
})

test('rejects an added uncovered item in both check and ratchet modes', () => {
  const path = 'backend/src/example.js'
  const expected = fileCoverage()
  const current = fileCoverage({ statements: tuple(4, 6) })

  /** @type {Array<'check' | 'ratchet'>} */
  const modes = ['check', 'ratchet']
  for (const mode of modes) {
    const evaluation = evaluateCoverage({
      summary: summary({ [path]: current }),
      baseline: baseline({ [path]: expected }),
      repositoryRoot: REPOSITORY_ROOT,
      mode,
    })

    assert.equal(evaluation.verdict, 'fail')
    assert.equal(evaluation.files[0].status, 'regression')
    assert.equal(evaluation.files[0].metrics.statements.status, 'regression')
    assert.equal(evaluation.files[0].metrics.statements.currentUncovered, 2)
    assert.equal(evaluation.files[0].metrics.statements.baselineUncovered, 1)
  }
})

test('rejects removal of covered code while misses remain', () => {
  const path = 'shared/src/example.js'
  const evaluation = evaluateCoverage({
    summary: summary({ [path]: fileCoverage({ statements: tuple(3, 4) }) }),
    baseline: baseline({ [path]: fileCoverage({ statements: tuple(4, 5) }) }),
    repositoryRoot: REPOSITORY_ROOT,
    mode: 'ratchet',
  })

  assert.equal(evaluation.verdict, 'fail')
  assert.equal(evaluation.files[0].metrics.statements.status, 'regression')
})

test('accepts removal of uncovered code only in ratchet mode', () => {
  const path = 'shared/src/example.js'
  const input = {
    summary: summary({ [path]: fileCoverage({ statements: tuple(4, 4) }) }),
    baseline: baseline({ [path]: fileCoverage({ statements: tuple(4, 5) }) }),
    repositoryRoot: REPOSITORY_ROOT,
  }

  assert.equal(evaluateCoverage(input).verdict, 'fail')
  assert.equal(evaluateCoverage({ ...input, mode: 'ratchet' }).verdict, 'pass')
  assert.equal(
    evaluateCoverage({ ...input, mode: 'ratchet' }).files[0].metrics.statements.status,
    'improvement'
  )
})

test('accepts fully covered code additions only in ratchet mode', () => {
  const path = 'frontend/src/todos/example.js'
  const input = {
    summary: summary({ [path]: fileCoverage({ statements: tuple(6, 6) }) }),
    baseline: baseline({ [path]: fileCoverage({ statements: tuple(4, 4) }) }),
    repositoryRoot: REPOSITORY_ROOT,
  }

  assert.equal(evaluateCoverage(input).verdict, 'fail')
  assert.equal(evaluateCoverage({ ...input, mode: 'ratchet' }).verdict, 'pass')
})

test('rejects one improved metric alongside one regressed metric', () => {
  const path = 'backend/src/example.js'
  const evaluation = evaluateCoverage({
    summary: summary({
      [path]: fileCoverage({
        statements: tuple(4, 4),
        branches: tuple(2, 4),
      }),
    }),
    baseline: baseline({ [path]: fileCoverage() }),
    repositoryRoot: REPOSITORY_ROOT,
    mode: 'ratchet',
  })

  assert.equal(evaluation.verdict, 'fail')
  assert.equal(evaluation.files[0].metrics.statements.status, 'improvement')
  assert.equal(evaluation.files[0].metrics.branches.status, 'regression')
})

test('treats zero-total metrics as one hundred percent', () => {
  const path = 'shared/src/constants.js'
  const zeroFunctions = fileCoverage({ functions: tuple(0, 0) })
  const exact = evaluateCoverage({
    summary: summary({ [path]: zeroFunctions }),
    baseline: baseline({ [path]: zeroFunctions }),
    repositoryRoot: REPOSITORY_ROOT,
  })
  const newlyUncovered = evaluateCoverage({
    summary: summary({ [path]: fileCoverage({ functions: tuple(0, 1) }) }),
    baseline: baseline({ [path]: zeroFunctions }),
    repositoryRoot: REPOSITORY_ROOT,
    mode: 'ratchet',
  })

  assert.equal(exact.verdict, 'pass')
  assert.equal(newlyUncovered.files[0].metrics.functions.status, 'regression')
})

test('reports new and deleted gated files as file-set changes', () => {
  const keptPath = 'backend/src/kept.js'
  const newPath = 'frontend/src/todos/new.js'
  const deletedPath = 'shared/src/deleted.js'
  const fullyCovered = fileCoverage({
    statements: tuple(5, 5),
    branches: tuple(2, 2),
    functions: tuple(1, 1),
    lines: tuple(5, 5),
  })
  const input = {
    summary: summary({ [keptPath]: fullyCovered, [newPath]: fullyCovered }),
    baseline: baseline({ [keptPath]: fullyCovered, [deletedPath]: fullyCovered }),
    repositoryRoot: REPOSITORY_ROOT,
  }

  const check = evaluateCoverage(input)
  assert.equal(check.verdict, 'fail')
  assert.deepEqual(check.changes.map(({ path, status }) => ({ path, status })), [
    { path: newPath, status: 'new-file' },
    { path: deletedPath, status: 'deleted-file' },
  ])
  assert.equal(evaluateCoverage({ ...input, mode: 'ratchet' }).verdict, 'pass')
})

test('ratchet refuses a new gated file with uncovered behavior', () => {
  const path = 'backend/src/new.js'
  const evaluation = evaluateCoverage({
    summary: summary({ [path]: fileCoverage() }),
    baseline: baseline({}),
    repositoryRoot: REPOSITORY_ROOT,
    mode: 'ratchet',
  })

  assert.equal(evaluation.verdict, 'fail')
  assert.equal(evaluation.files[0].status, 'new-file')
  assert.equal(evaluation.files[0].outcome, 'regression')
})

test('normal check rejects a zero-total file-set change that ratchet may accept', () => {
  const path = 'shared/src/types-only.js'
  const empty = fileCoverage({
    statements: tuple(0, 0),
    branches: tuple(0, 0),
    functions: tuple(0, 0),
    lines: tuple(0, 0),
  })
  const input = {
    summary: summary({ [path]: empty }),
    baseline: baseline({}),
    repositoryRoot: REPOSITORY_ROOT,
  }

  const check = evaluateCoverage(input)
  assert.equal(check.verdict, 'fail')
  assert.equal(check.files[0].status, 'new-file')
  assert.equal(evaluateCoverage({ ...input, mode: 'ratchet' }).verdict, 'pass')
})

test('normalizes and orders paths while distinguishing direct and recursive rollups', () => {
  const backendDirect = fileCoverage({ statements: tuple(3, 5) })
  const backendNested = fileCoverage({ statements: tuple(7, 8) })
  const sharedNested = fileCoverage({ statements: tuple(2, 2) })
  const files = {
    'shared/src/z.js': sharedNested,
    'backend/src/todos/b.js': backendNested,
    'backend/src/a.js': backendDirect,
  }
  const currentSummary = summary(files)
  currentSummary.total = fileCoverage({ statements: tuple(12, 15) })

  const evaluation = evaluateCoverage({
    summary: currentSummary,
    baseline: baseline(files),
    repositoryRoot: `${REPOSITORY_ROOT}/nested/..`,
  })

  assert.deepEqual(evaluation.files.map(({ path }) => path), [
    'backend/src/a.js',
    'backend/src/todos/b.js',
    'shared/src/z.js',
  ])
  assert.deepEqual(evaluation.global.statements, tuple(12, 15))
  assert.deepEqual(evaluation.rollups.backend.direct.statements, tuple(3, 5))
  assert.deepEqual(evaluation.rollups.backend.recursive.statements, tuple(10, 13))
  assert.deepEqual(evaluation.rollups.shared.recursive.statements, tuple(2, 2))
  assert.deepEqual(evaluation.rollups.frontend.recursive.statements, tuple(0, 0))
})

test('renders escaped Markdown and HTML in the canonical evidence order', () => {
  const hostilePath = 'shared/src/a&<b>|.js'
  const files = { [hostilePath]: fileCoverage({ functions: tuple(0, 0) }) }
  const evaluation = evaluateCoverage({
    summary: summary(files),
    baseline: baseline(files),
    repositoryRoot: REPOSITORY_ROOT,
    provenance: {
      revision: 'abc<&>|`',
      dirty: true,
      generatedAt: '2026-08-08T12:34:56.000Z',
      scope: 'merged unit + Storybook',
    },
    sourceEvidence: {
      verdict: 'pass',
      issues: [],
      categoryCounts: {
        'logic-ratchet': 1,
        'storybook-ui': 1,
        'e2e-bootstrap': 1,
        'test-support': 0,
        'type-only': 1,
      },
      sources: [
        { path: hostilePath, category: 'logic-ratchet', rationale: 'exact coverage' },
        { path: 'frontend/src/App.jsx', category: 'storybook-ui', rationale: 'browser stories' },
      ],
      ui: [{
        path: 'frontend/src/App.jsx',
        evidence: 'frontend/src/App.stories.jsx',
        declaredStories: 2,
        declaredPlays: 2,
        executedStories: 2,
        coverage: fileCoverage({ branches: tuple(2, 3) }),
      }],
      uiTotals: fileCoverage({ branches: tuple(2, 3) }),
    },
  })

  const markdown = renderCoverageMarkdown(evaluation)
  assert.match(markdown, /abc&lt;&amp;&gt;\\\|\\`/)
  assert.match(markdown, /shared\/src\/a&amp;&lt;b&gt;\\\|\.js/)
  assert.match(markdown, /0\/0 \(100\.00%\)/)
  assert.match(markdown, /UI source coverage \(informational\)/)
  assert.match(markdown, /frontend\/src\/App\.jsx/)
  assert.match(markdown, /2\/2 stories executed/)

  const html = renderCoverageHtml(evaluation)
  assert.doesNotMatch(html, /abc<&>/)
  assert.doesNotMatch(html, /a&<b>/)
  assert.match(html, /abc&lt;&amp;&gt;\|&#96;/)
  assert.match(html, /shared\/src\/a&amp;&lt;b&gt;\|\.js/)
  assert.match(html, /href="index\.html"/)
  assert.match(html, /UI source coverage \(informational\)/)
  assert.match(html, /Source evidence ownership/)
  assert.match(html, /frontend\/src\/App\.stories\.jsx/)
  assert.match(html, /class="ui-table"/)

  const orderedHeadings = [
    'Coverage evidence',
    'Gated logic totals',
    'Gated logic recursive workspace rollups',
    'Source evidence ownership',
    'UI source coverage (informational)',
    'Changes requiring action',
    'Gated files',
    'Istanbul explorer',
  ]
  let previous = -1
  for (const heading of orderedHeadings) {
    const position = html.indexOf(heading)
    assert.ok(position > previous, `${heading} should follow the previous section`)
    previous = position
  }
})

test('creates a deterministic exact baseline without source revision state', () => {
  const generated = createCoverageBaseline({
    summary: summary({
      'shared/src/z.js': fileCoverage(),
      'backend/src/a.js': fileCoverage({ functions: tuple(0, 0) }),
    }),
    repositoryRoot: REPOSITORY_ROOT,
  })

  assert.equal(generated.schemaVersion, 1)
  assert.match(generated.notice, /Generated.*coverage:ratchet.*Do not edit/)
  assert.deepEqual(Object.keys(generated.files), [
    'backend/src/a.js',
    'shared/src/z.js',
  ])
  assert.deepEqual(generated.files['backend/src/a.js'].functions, tuple(0, 0))
  assert.equal('revision' in generated, false)
})
